sudo: false
language: php
dist: trusty

matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  - php: hhvm
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.2
  - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script: composer install

script:
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - phpenv global 5.5
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    
notifications:
  email: false    
