sudo: false
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

before_script: composer install

script: phpunit --coverage-text --coverage-clover=coverage.clover --configuration ./phpunit-travis.xml.dist

after_script:
    - phpenv global 5.5
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    
notifications:
    email: false    
